description: "\nThe \u201Cproducts_df\u201D table is a master list of every item the\
  \ company sells.  \nIt records each product\u2019s brand, category, cost, price,\
  \ customer rating, and how many units are currently in stock.\n\n**Why it matters**\
  \  \n- Keeps the product catalog up\u2011to\u2011date for pricing, inventory, and\
  \ sales planning.  \n- Provides the data needed for margin calculations, stock\u2011\
  reorder decisions, and marketing targeting.\n\n**Typical users and uses**  \n- Merchandisers\
  \ set prices and promotions based on cost, price, and rating.  \n- Supply\u2011\
  chain planners monitor stock levels and trigger replenishment.  \n- Finance teams\
  \ compute profitability by brand or category.  \n- Marketing identifies highly rated,\
  \ high\u2011margin products for campaigns.\n\n**Key business links**  \n- Shows\
  \ which product was sold in each order.  \n- Connects to supplier information for\
  \ cost updates.  \n- Relates to warehouse inventory records to track actual stock\
  \ levels.\n"
fields:
  brand:
    data_type: VARCHAR
    description: Product brand name
    null_count: 0
    unique_values:
      Adidas: 34
      Apple: 44
      IKEA: 43
      Nike: 38
      Samsung: 41
  category:
    data_type: VARCHAR
    description: Product category classification
    null_count: 0
    unique_values:
      Clothing: 65
      Electronics: 46
      Home: 50
      Sports: 39
  cost:
    data_type: DECIMAL
    description: Product cost basis in USD
    null_count: 0
    statistics:
      max: 177.8
      mean: 35.74065
      min: 5.22
  price:
    data_type: DECIMAL
    description: Product retail price in USD
    null_count: 0
    statistics:
      max: 386.26
      mean: 56.91210000000001
      min: 10.2
  product_id:
    data_type: INTEGER
    description: Unique product identifier
    null_count: 0
    statistics:
      max: 200.0
      mean: 100.5
      min: 1.0
  rating:
    data_type: DECIMAL
    description: Average customer rating (1-5 scale)
    null_count: 0
    statistics:
      max: 4.99
      mean: 2.9585000000000004
      min: 1.02
  stock_quantity:
    data_type: INTEGER
    description: Current inventory quantity available
    null_count: 0
    statistics:
      max: 998.0
      mean: 502.745
      min: 6.0
table_name: products_df
